add a simple dockerfile
Sh1Yo/x8 pull request #29
Opened 2022-12-28 15:44 UTC by amiremohamadi

can be simply used like this:
```bash
$ ls
input.txt

$ docker run -it -v $PWD:/app x8 -u https://4rt.one/level1 -w /app/input.txt
```

or

```bash
$ cat input.txt | docker run -i x8 -u https://4rt.one/level1 -w
```

2022-12-28 18:43 UTC, Sh1Yo requested changes
Hi, thanks for the pull request. I also thought that adding a Dockerfile would be a good idea but didn't have time to create it. There's one suggestion tho, I think it's better to grab the latest release from github(https://github.com/sh1yo/x8/releases/latest/download/x86_64-linux-x8.gz) instead of compiling it every time.

2022-12-30 14:01 UTC, amiremohamadi commented
thanks for your response. actually the whole point of having a dockerfile is to make it possible to run everywhere. by forcing it to download `x86_64-linux` version, it won't work on for example a raspberry pi or sth like that.
I think the better approach would be pushing the docker image to https://hub.docker.com.

2023-01-07 12:18 UTC, Sh1Yo commented
Thanks for the response. That makes sense, at least when there are not a lot of precompiled binaries available. Still, your Dockerfile needs a fix - the Cargo.lock file isn't within the repository so it will throw an error after a clone. Also, I think it's better to clean temp files with `cargo clean` after the building. Building files take a lot of storage (over 0.5GB), and I don't push updates often to rebuild it anyway.

2023-01-08 06:12 UTC, amiremohamadi commented
oop! you're correct, we don't have `Cargo.lock` within the repo. though, rust documents encourage to commit `Cargo.lock` into repository [[link]](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) (should we?).

about calling `cargo clean`, we have a multi-stage Dockerfile that only copies x8 binary in the second stage. so we don't need to call it (because in the second stage everything is cleared and we don't have any temp files). the result will be a tiny and lightweight image.

2023-01-08 06:30 UTC, Sh1Yo commented
It looks like I should add it to prevent possible conflicts :thinking: It will ruin github stats a bit though.. 

Again, thanks for the pr. I'll add Cargo.lock and merge it today.

2023-01-08 06:33 UTC, merged

2024-10-04 22:22 UTC, Mers4d4831 commented
Thanks.